<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>time</string>
	</array>
	<key>name</key>
	<string>TimeTracker</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#link</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.header.time</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(#.*$\n?)</string>
			<key>name</key>
			<string>meta.header-item.time</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.item.time</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.item-tally.time</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^-\s+.*(\[[\dap,:\-\. ]*\])\s?(\([\d\.]*\))?.*?$</string>
			<key>name</key>
			<string>meta.line-item.time</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.item-aux.time</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.tag.time</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\t+(-\s+.*(\s@SEO\s)?.*)</string>
			<key>name</key>
			<string>meta.line-item-aux.time</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.total.time</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.item-tally.time</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(\++\s+.*:\s([\d\.]+))$</string>
			<key>name</key>
			<string>meta.line-total.time</string>
		</dict>
	</array>
	<key>repository</key>
	<dict/>
	<key>scopeName</key>
	<string>text.plain.time</string>
	<key>uuid</key>
	<string>391A0633-D21C-40D4-985C-7A5FF8627E6F</string>
</dict>
</plist>
